### ISSUE TITLE
Torrent-to-Web Version 1.2.0 Not Working With Firefox ESR 52.5.0

### ISSUE THREAD

**Issue by BarnetHill** [DASPRiD/Torrent-to-Web#14]
I have just been automatically upgraded to Torrent to Web Version 1.20. I am running Firefox 52.5.0 ESR 32 bit on a win 7 Pro 64 bit machine.

When I right click on a torrent download icon I no longer have the "Send to Torrent Client" menu item.

I downgraded to Version 1.10 and now the  "Send to Torrent Client" menu item is back again and Torrent to web is working

**Comment by DASPRiD** [comment]
Thanks for the information, fixed in 1.2.1!
