### ISSUE TITLE
Error While Uploading Torrent File

### ISSUE THREAD

**Issue by BarnetHill** [DASPRiD/Torrent-to-Web#25]
I have a win 7 Pro 64 bit and Firefox 60.8.0 ESR (32 bit).  I am running a whatbox seedbox.

I am running Torrent to Web 1.30.0

When I see a torrent that I need,  I right click on the download button and then click on the Send to Torrent Client icon.

I see the Retrieving Torrent window and then I get an Error While Uploading Torrent File window.

This used to work on this machine.  I have an identical win 7 machine and Torrent to Web is working fine on that one.

I tried removing and reinstalling Torrent to Web but it didn't fix the issue. Is there any way to see what the error is or any way to fix this problem?

thanks

**Comment by DASPRiD** [comment]
You can go to [about:debugging](about:debugging) and enable add-on debugging there, see:
https://developer.mozilla.org/en-US/docs/Tools/about:debugging#Enabling_add-on_debugging

**Comment by BarnetHill** [comment]
I am not a software guy so this is getting way beyond my skill level.  Is there anything that you suggest I should be doing to get Torrent to Web working again?

thanks

**Comment by DASPRiD** [comment]
Well, since it's working on your other machine, is that one also running version 1.3.0 against the same seedbox? Also, which torrent client is your seedbox running.

**Comment by BarnetHill** [comment]
It is running ruTorrent

**Comment by BarnetHill** [comment]
I just deleted a file on the seedbox so the browser is talking to ruTorrent

**Comment by felfert** [comment]
So there is actually no bug? It is working?

**Comment by BarnetHill** [comment]
No it is not working and there is a bug       I just used the browser to bring up the ruTorrent file delete menu, so that I can see if the browser can talk to the ruTorrent.

**Comment by BarnetHill** [comment]
I am fumbling around...I am a hardware engineeer   lol

**Comment by BarnetHill** [comment]
The torrent file does not get uploaded to the seedbox

**Comment by BarnetHill** [comment]
It says Error While Uploading Torrent File

**Comment by felfert** [comment]
I **really** encourage you to try debugging. It is the only way to get accurate info about what is happening. It is not that hard:

1. Go to about:debugging
2. Check the checkbox at the top of the page "Enable addon debugging"
3. Find the Web To Torrent addon in the list below.
4. Click on the "debug" link.
5. A separate debugger window opens. In that window:
6. Select the "network" tab at the top tab-bar.
7. Go back to your regular window and attempt to send a torrent
8. After that failed, go back to the debugger window.

There should be at least 2 new lines listed there. The first is the download request from wherever you download the torrent. The second one is the intersting one. Tell us what is listed there.

**Comment by felfert** [comment]
Actually, it is not necessarily the second line. If your rutorrent redirects, it might be the third. In any case, the interesting line is the **last** one in the debugger.
It should show a number on the leftmost column. We need to know that number.

**Comment by felfert** [comment]
It is probably some 4xx.

**Comment by felfert** [comment]
If it is a 404, that means "Not found" then check the URL in the Addon settings.
If it is a 401 or 403, then your username/password is wrong in the Addon settings.

**Comment by BarnetHill** [comment]
I got a status 200 for the first line and the second line had no number

**Comment by felfert** [comment]
Hmm, if there's no number, then that request is unfinished. That can mean that either a firewall is blocking the request or DNS is not working for that machine. Do you use name or IP-Address in the URL of the addon-settings?

**Comment by BarnetHill** [comment]
I can send u a screen capture if u have somewhere secure to send it

**Comment by BarnetHill** [comment]
I used the name on the settings

**Comment by felfert** [comment]
Well, if it is unfinished, the the reason is **very** likely out of the scope of debuggin in FF anyway. So that would not help

**Comment by BarnetHill** [comment]
the first connection is green and says secure and the second connection is red and says unsecure

**Comment by felfert** [comment]
Then try the IP instead. If it works after that. The DNS is the culprit. Otherwise: firewall
Insecure means that you used http to connect to your seedbox, not https.

**Comment by felfert** [comment]
Ahhh wait a moment. *That* can be the reason for unfinished as well!!!

**Comment by felfert** [comment]
You can contact me via the email address in my github-profile.

**Comment by BarnetHill** [comment]
will..I tried the url but it was still the same - not working

I sent u a screen capture by e-mail

**Comment by BarnetHill** [comment]
I meant I tried the ip address and it made no difference

**Comment by felfert** [comment]
Hmm nothing received yet?!

**Comment by DASPRiD** [comment]
He sent it to me.

![Torrent_01](https://user-images.githubusercontent.com/233300/61657755-fe815600-acc3-11e9-9183-1ee56a058ef8.JPG)

**Comment by felfert** [comment]
Oh :-)

**Comment by BarnetHill** [comment]
Sorry I didn't notice that there were 2 of you

**Comment by BarnetHill** [comment]
I don't if that was of any help

**Comment by felfert** [comment]
All the failed requests are 0 bytes. This is most likely a general network problem.
You told earlier, that you can rech your seedbox in a regular browser tab. If that's true, then **carefully** compare that URL to the URL in the failed xhr requests. There **must** be some difference.

**Comment by felfert** [comment]
Well, I went to your seedbox in my browser and it immediately redirects to https. So: In the Addon-Settings, you most likely have your seedbox URL mistyped http:// instead of https://

**Comment by BarnetHill** [comment]
I have the ip address numbers in there right now...let me go back to text and double check

**Comment by felfert** [comment]
http**s**//...

**Comment by felfert** [comment]
And if it is https, then you better should use the name instead of IP, because then the certificate of the server actually matches the name and FF does not get confused.

**Comment by BarnetHill** [comment]
Thanks I put the text back in and it is working now.  So good news

I found something weird going on where my Firefox download directory was 00_Temp but it was being displayed as  Downloads but files directed to 00_Temp were  still going there.   When I looked at Folder Properties the General tab had the name Downloads but the Sharing tab had the name 00_Temp.  Very strange.  I changed it's name back to 00_Temp but also directed Firefox to use a different folder for the time being    

The 00_Temp Icon in Windows Explorer has the Folder symbol but with a blue downward arrow on it.  What does the blue downward arrow mean?

**Comment by felfert** [comment]
That you have some recent downloads in there. Just click on it and it shows them.

**Comment by felfert** [comment]
@DASPRiD Ok, can be closed :-)

**Comment by BarnetHill** [comment]
Yes thanks for all your help today

**Comment by DASPRiD** [comment]
@felfert Also thanks for helping him out – I'm more or less on vacation right now ;)
