### ISSUE TITLE
determineFilename not recognizing some files

### ISSUE THREAD

**Issue by gurt-il** [DASPRiD/Torrent-to-Web#3]
Hi

I want to thank you for the addon, is really simple and great.

I have a small problem, One of my favorite sites are responding with a header in the followed format:
`attachment; filename*=windows-1255''somefile.torrent`.

The filename regex (`/filename=(?:"([^"]+)"|([^;]+);?)/`) are assuming that the file name are started with `filename=` and the `filename*=` is missed.

Can you please fix it?

Thanks

**Comment by DASPRiD** [comment]
I'll look into it in the next few days, thanks for the detailed bug report!
