### ISSUE TITLE
Pop Up time out

### ISSUE THREAD

**Issue by returnvisit** [DASPRiD/Torrent-to-Web#38]
Any way to make the "Magnet link sent" pop up notification smaller or adjustable time out. I'ts kind of big and stays too long. Thanks!

**Comment by DASPRiD** [comment]
That notification is coming from your operating system, so size wise, we can't do anything about that. Not sure about the timeout.

@felfert Care to have a look at this?

**Comment by felfert** [comment]
No way. [FF's notification API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications) does not provide a way to set a time out or display style.
The only thing possible, is switching notifications on or off in general.

**Comment by returnvisit** [comment]
Thanks for checking!
