### ISSUE TITLE
Add please deluge 1.3.15

### ISSUE THREAD

**Issue by ramlaxman** [DASPRiD/Torrent-to-Web#4]
Please add support deluge 1.3.15

http://dev.deluge-torrent.org/wiki/Download

These one is nice, rising  and clean client with cross platform.

**Comment by Yoposoc** [comment]
I would also like to request deluge webclient support.

**Comment by DASPRiD** [comment]
@Pbroc is currently working on this issue: https://github.com/DASPRiD/Torrent-to-Web/pull/2

**Comment by DASPRiD** [comment]
Fixed via #2
