### ISSUE TITLE
Send to qBittorrent not working after 3/10 update

### ISSUE THREAD

**Issue by runrunner** [DASPRiD/Torrent-to-Web#46]
I've been using Torrent-to-Web for a while and I love it. I'm hitting an issue where I get the "Failed to send torrent to client" popup on every torrent.

**Background:**
I recently noticed that it disappeared from my context menu.

After digging in a bit, I found that my profiles were removed from the extension options. I set them back up (no big deal).

When I went to download a file I got the error noted above.

Turning on the extension debugger, I see that I successfully GET the file, however when it attempts to login, it gets a 400 Bad Request in response.

Here's a screenshot with some bits blanked out for privacy.
My Domain/Host/Address fields are all of the form `IP:PORT`
In my Profile Options, the URL is of the form `http://IP:PORT`

![image](https://user-images.githubusercontent.com/101476821/158032846-db8e56c5-856d-47d3-8ad3-0826e1c80379.png)

**Comment by DASPRiD** [comment]
Thanks for the report, the fixed version was just released and approved.

**Comment by runrunner** [comment]
Thank you so much!!
