### ISSUE TITLE
Cannot create a transmission profile without login or password

### ISSUE THREAD

**Issue by eternal-sorrow** [DASPRiD/Torrent-to-Web#47]
![2022-03-25-034245](https://user-images.githubusercontent.com/4847726/159977786-91866f3d-a903-4b49-b673-f5a3697de235.png)

**Comment by DASPRiD** [comment]
You can insert dummy data in there, although I'd highly recommend to not have an unprotected Transmission web UI running.

**Comment by eternal-sorrow** [comment]
If I insert dummy data, it does not work. Gives an error. You don't recommend it even if it's on localhost?

**Comment by DASPRiD** [comment]
If it's localhost, can't you just download the .torrent file normally and "open with Transmission"?

**Comment by eternal-sorrow** [comment]
I can't. I don't have a GUI transmission client. Only a transmission daemon running in the background.

**Comment by DASPRiD** [comment]
I see. Well, it shouldn't hurt to set up username and password for the daemon then :)

**Comment by eternal-sorrow** [comment]
I'll rather use another extension...
