### ISSUE TITLE
Add support for SSL

### ISSUE THREAD

**Issue by MacQwerty** [DASPRiD/Torrent-to-Web#6]
https://IP-adress/rutorrent/ isn't working, while http://IP-adress/rutorrent/ is working, so I suppose SSL isn't implemented yet. Would be a much appreciated feature!

**Comment by DASPRiD** [comment]
I'm using it with HTTPS and rutorrent, so that is working fine.There must be something else about your SSL setup, I suppose.

**Comment by MacQwerty** [comment]
Hm, that's strange... I will look into it later! Thanks anyway:)
