### ISSUE TITLE
Add support for magnet links

### ISSUE THREAD

**Issue by shadww** [DASPRiD/Torrent-to-Web#8]
Hi ! Thanks for the  awesome addon on FF.
Can magnet links support be added to it?

**Comment by ValTer25** [comment]
Hello
it is possible to add support of utorrent server and that when clicking by the left mouse button the reference to torrent the file was automatically added in downloading on remote utorrent server?

**Comment by DASPRiD** [comment]
I never looked into magnet links TBH. If someone could provide a PR for that, it could surely be implemented.

**Comment by Garbonzo17** [comment]
Yes, Magnets are a must.

**Comment by felfert** [comment]
I think handling of magnet links is even easier that downloading torrents. The URI should just be handed over to the torrent client verbatim. No download/upload sequence needed. The actual handling depends on the torrent client however. I'm a ruTorrent user and could offer to investigate how it's API works regarding magnet. For other clients, somebody else should answer that.

**Comment by DASPRiD** [comment]
If we add such a feature, it should clearly be supported by all adapters we have, except for client which have no magnet support at all. In the cases where there is no client-side support for magnet links, we should either hide the selection for that or show an error when someone tries to send a magnet link to an unsupported client.

**Comment by felfert** [comment]
> If we add such a feature, it should clearly be supported by all adapters...
Agreed. In the meantime, I researched a little and already have the changes for ruTorrent and transmission here. Still have to figure out deluge... I will submit another PR which adds this feature. For that, It would be **really helpful**, if you merge my referrer-PR, otherwise another PR against the same master most certainly will produce merge conflicts in background/main.js
